server {
    listen 80;

    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # 🔥 Proxy API Python
    location /api/ {
        proxy_pass http://python_api:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 🔥🔥🔥 CORRECTION CRITIQUE : IMAGES ML
    location /analysis_exports/ {
        alias /app/service/analysis_exports/;
        autoindex on;
        access_log off;
        expires 1h;
        add_header Cache-Control "public";
    }

    location ~ /\. {
        deny all;
    }
}