services:

  nginx:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - sfe_net

  php:
    build:
      context: ./php
    container_name: php_fpm
    volumes:
      - ./app:/var/www/html
    networks:
      - sfe_net
    depends_on:
      - db

  db:
    image: mariadb:10.11
    container_name: mariadb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sfe_net

  python:
    build: 
      context: ./python
    container_name: python_service
    volumes:
      - ./app:/var/www/html
    networks:
      - sfe_net

volumes:
  db_data:

networks:
  sfe_net:
